### ISSUE TITLE
[Question] Emoji's names between `:`

### ISSUE THREAD

**Issue by joex92** [TruMiner/Twemojis-In-Minecraft#1]
Hi,
Would this also work with emoji's names between `:`? like `:thumbsup:` on chat would show as 👍🏼 ?

**Comment by Terminxa** [comment]
Unfortunately this isn't possible with resource packs, but I have three methods that may help:

- if you are on windows you can press Windows Key + . and it will open the emoji menu. search the emoji and it will paste into the chat

- if you are on mac you can press Command + Control + Space to open the emoji menu.

- you can install the emoji type mod (https://modrinth.com/mod/emoji-type) and manually add that for every emoji.
