### ISSUE TITLE
Zero-width joiner and variation selector characters not included in pack.

### ISSUE THREAD

**Issue by Owehttamy** [TruMiner/Twemojis-In-Minecraft#2]
When trying to send any "complex" emoji, such as two men with set skin tones kissing (👨🏿‍❤️‍💋‍👨🏻), the game will output this:
![image](https://user-images.githubusercontent.com/47429979/229398359-126bc833-f462-4f42-b068-806fd11311bf.png)
This impacts every emoji with a set skin tone, every flag, and every other emoji that uses more than one existing emoji, such as 🌦️

**Comment by Terminxa** [comment]
This is a minecraft limitation unfortunately, there nothing I can do. If something changes I will fix it.
