### ISSUE TITLE
Fluent Emoji Resource Pack

### ISSUE THREAD

**Issue by pizzav-xyz** [TruMiner/Twemojis-In-Minecraft#3]
coiul;d you make one for the microsoft fluent emojis

https://fluentemoji.com
https://animated-fluent-emoji.vercel.app

**Comment by Terminxa** [comment]
I have actually thought about this before, and it may be something I will do in the future. It's not planned for now, but this may change in the future.

**Comment by Terminxa** [comment]
https://github.com/TruMiner/FluentEmoji-Visibility
